//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientWindowsForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/PhoneRepository.Models")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDist", ReplyAction="http://tempuri.org/IService1/GetDistResponse")]
        WcfClientWindowsForm.ServiceReference1.Contact[] GetDist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDist", ReplyAction="http://tempuri.org/IService1/GetDistResponse")]
        System.Threading.Tasks.Task<WcfClientWindowsForm.ServiceReference1.Contact[]> GetDistAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDict", ReplyAction="http://tempuri.org/IService1/AddDictResponse")]
        string AddDict(WcfClientWindowsForm.ServiceReference1.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDict", ReplyAction="http://tempuri.org/IService1/AddDictResponse")]
        System.Threading.Tasks.Task<string> AddDictAsync(WcfClientWindowsForm.ServiceReference1.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdDict", ReplyAction="http://tempuri.org/IService1/UpdDictResponse")]
        string UpdDict(WcfClientWindowsForm.ServiceReference1.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdDict", ReplyAction="http://tempuri.org/IService1/UpdDictResponse")]
        System.Threading.Tasks.Task<string> UpdDictAsync(WcfClientWindowsForm.ServiceReference1.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDict", ReplyAction="http://tempuri.org/IService1/DelDictResponse")]
        string DelDict(WcfClientWindowsForm.ServiceReference1.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDict", ReplyAction="http://tempuri.org/IService1/DelDictResponse")]
        System.Threading.Tasks.Task<string> DelDictAsync(WcfClientWindowsForm.ServiceReference1.Contact contact);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfClientWindowsForm.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfClientWindowsForm.ServiceReference1.IService1>, WcfClientWindowsForm.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfClientWindowsForm.ServiceReference1.Contact[] GetDist() {
            return base.Channel.GetDist();
        }
        
        public System.Threading.Tasks.Task<WcfClientWindowsForm.ServiceReference1.Contact[]> GetDistAsync() {
            return base.Channel.GetDistAsync();
        }
        
        public string AddDict(WcfClientWindowsForm.ServiceReference1.Contact contact) {
            return base.Channel.AddDict(contact);
        }
        
        public System.Threading.Tasks.Task<string> AddDictAsync(WcfClientWindowsForm.ServiceReference1.Contact contact) {
            return base.Channel.AddDictAsync(contact);
        }
        
        public string UpdDict(WcfClientWindowsForm.ServiceReference1.Contact contact) {
            return base.Channel.UpdDict(contact);
        }
        
        public System.Threading.Tasks.Task<string> UpdDictAsync(WcfClientWindowsForm.ServiceReference1.Contact contact) {
            return base.Channel.UpdDictAsync(contact);
        }
        
        public string DelDict(WcfClientWindowsForm.ServiceReference1.Contact contact) {
            return base.Channel.DelDict(contact);
        }
        
        public System.Threading.Tasks.Task<string> DelDictAsync(WcfClientWindowsForm.ServiceReference1.Contact contact) {
            return base.Channel.DelDictAsync(contact);
        }
    }
}
